# -*- coding: utf-8 -*-
"""Application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sleBp0jr4AYYQYAWDg3Q9T7O1Lu3A9Or
"""

!pip install -U scikit-learn pandas openpyxl gradio

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
import numpy as np
import gradio as gr

TEXT_COL = "text"
LABEL_COL = "label"
DATA_PATH = "Cleaned_Data.xlsx"

df = pd.read_excel(DATA_PATH)
print("Data shape:", df.shape)
print("Columns:", df.columns.tolist())

x = df[TEXT_COL].astype(str)
y = df[LABEL_COL].astype(str)

tfidf_char = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3, 5),
    max_features=30000,
    lowercase=True,
)

char_tfidf_svm = Pipeline([
    ("tfidf_char", tfidf_char),
    ("clf", LinearSVC())
])

char_tfidf_svm.fit(x, y)
print("Model trained on all data.")

import joblib
joblib.dump(char_tfidf_svm, "char_tfidf_svm_best.joblib")
print("Saved model to char_tfidf_svm_best.joblib")

model = char_tfidf_svm

def predict_ai_or_human(text: str):
    if not text or not text.strip():
        return {"label": "N/A", "conf": "Please enter some text first."}
    label = model.predict([text])[0]
    score = model.decision_function([text])[0]
    prob_ai_raw = 1 / (1 + np.exp(-score))
    classes = model.named_steps["clf"].classes_
    if classes[1] == "ai":
        p_ai = prob_ai_raw
    else:
        p_ai = 1 - prob_ai_raw
    if label == "ai":
        main_label = "AI"
    else:
        main_label = "Human"

    conf_msg = f"Estimated probability this is AI-written: {p_ai:.3f}"

    return {"label": main_label, "conf": conf_msg}

def gradio_interface(text):
    result = predict_ai_or_human(text)
    return result["label"], result["conf"]

demo = gr.Interface(
    fn=gradio_interface,
    inputs=gr.Textbox(lines=10, label="Input text"),
    outputs=[
        gr.Label(label="Predicted class"),
        gr.Textbox(label="Confidence / extra info")
    ],
    title="AI vs Human Text Detector",
)

demo.launch()
